In [5]:
import pandas as pd
from sqlalchemy import create_engine

In [6]:
engine = create_engine('mysql://9cb054_testdb:paladinlol!@MYSQL5008.Smarterasp.net:3306/db_9cb054_testdb')

# engine = create_engine('mysql://dsi_student:9cb054_testdb@dsi.http://mysql5008.smarterasp.net/:3306/db_9cb054_testdb')

In [7]:
pd.read_sql("SHOW tables", con=engine)

   Tables_in_db_9cb054_testdb
0                        card
1                    carddraw
2                    cardturn
3                        deck
4                        game
5                        hand
6                minionattack
7                mulligancard
8                opponentdeck
9            opponentdeckcard
10                       turn
11                       user
12                   userdeck
13               userdeckcard

In [9]:
sql = """
SELECT * FROM game
WHERE GameType = "Constructed" AND GameOpponent != "The Innkeeper"
ORDER BY GameID DESC
"""

train = pd.read_sql(sql, con=engine)
train.head()

,GameID,GameUserName,GameUserClass,GameOpponent,GameOpponentClass,GameStart,GameEnd,GameType,GameRank,Victory,Coin,ReplayText
0,1425,Jayford,Guldan,McBain,Thrall,2016-05-19 20:28:50,2016-05-19 20:28:51,Constructed,0, , ,Opponent drew a card#Opponent drew a card#Oppo...
1,1422,thall,Thrall,Silent,Anduin Wrynn,2016-05-15 18:03:15,2016-05-15 18:03:15,Constructed,0,,,Opponent drew a card#Opponent drew a card#Oppo...
2,1418,Jayford,Uther Lightbringer,Reggie,Valeera Sanguinar,2016-05-15 15:23:18,2016-05-15 15:23:18,Constructed,0, ,,You draw Ysera#You draw Shifter Zerus#You dr...
3,1417,Jayford,Uther Lightbringer,tottotz,Thrall,2016-05-02 22:26:53,2016-05-02 22:26:54,Constructed,0,, ,You draw Consecration#You draw Solemn Vigil#...
4,1416,Jayford,Uther Lightbringer,Hotrod19,Rexxar,2016-05-02 22:07:38,2016-05-02 22:07:39,Constructed,0,,,You draw Selfless Hero#You draw Aldor Peacek...

In [10]:
sql = """
SELECT * FROM game
WHERE GameOpponent != "The Innkeeper"
ORDER BY GameID DESC
"""

train1 = pd.read_sql(sql, con=engine)
train1.head()

,GameID,GameUserName,GameUserClass,GameOpponent,GameOpponentClass,GameStart,GameEnd,GameType,GameRank,Victory,Coin,ReplayText
0,1425,Jayford,Guldan,McBain,Thrall,2016-05-19 20:28:50,2016-05-19 20:28:51,Constructed,0, , ,Opponent drew a card#Opponent drew a card#Oppo...
1,1422,thall,Thrall,Silent,Anduin Wrynn,2016-05-15 18:03:15,2016-05-15 18:03:15,Constructed,0,,,Opponent drew a card#Opponent drew a card#Oppo...
2,1418,Jayford,Uther Lightbringer,Reggie,Valeera Sanguinar,2016-05-15 15:23:18,2016-05-15 15:23:18,Constructed,0, ,,You draw Ysera#You draw Shifter Zerus#You dr...
3,1417,Jayford,Uther Lightbringer,tottotz,Thrall,2016-05-02 22:26:53,2016-05-02 22:26:54,Constructed,0,, ,You draw Consecration#You draw Solemn Vigil#...
4,1416,Jayford,Uther Lightbringer,Hotrod19,Rexxar,2016-05-02 22:07:38,2016-05-02 22:07:39,Constructed,0,,,You draw Selfless Hero#You draw Aldor Peacek...

In [15]:
train.GameOpponent.value_counts()

                17
Crixus          12
Nothing         11
Crimzig          8
Fibonacci        6
Pluffles         5
lionelsnarff     5
Azalin           4
chandyland       4
HeliosTU         4
YeahHoe          4
EightInches      4
JAB              4
MrHuDat          4
FriedChicken     3
Sebavh           3
deathstarV3      3
Silent           3
Aaron            3
Nyrlathoderp     3
KBril            3
TwilightOwl      3
Iapeto           3
Irronman         3
IronAron         3
Wrath            3
chuvac01         3
sexybeast        3
Akogare          3
Loxodontes       3
                ..
joe              1
agwa             1
Weiro            1
LucasFZ          1
James            1
Bambamdwadle     1
co1e             1
Ether            1
derptank         1
AJugOrNot        1
Sura             1
FunkyMath        1
Hugostiglitz     1
Zadkiel          1
Deezenutz        1
Train            1
macroshin        1
Dalne            1
Diablor          1
UchihaSaske      1
DreamCrusher     1
Battòjutsu       1
BeerWizard       1
Volchishka       1
Coglorin         1
MrSquirrely      1
RainBuckets      1
rinoranchero     1
sneyldat         1
HappyFeet        1
Name: GameOpponent, dtype: int64

In [14]:
train1.GameOpponent.value_counts()

                89
Crixus          12
Juice           11
John Crofts     11
Nothing         11
Crimzig          8
Rooftrellen      8
Sean Ryan        6
Fibonacci        6
Pluffles         5
Akogare          5
wendar           5
lionelsnarff     5
Azalin           4
chandyland       4
Dota2Better      4
HeliosTU         4
YeahHoe          4
Odius            4
JAB              4
MrHuDat          4
EightInches      4
Silent           3
Nyrlathoderp     3
deathstarV3      3
chuvac01         3
sexybeast        3
FriedChicken     3
Aristocrat       3
Loxodontes       3
                ..
lostforce        1
liimujx          1
Jackmonkey       1
solano           1
Ryuk             1
Karnaldo         1
Zyfor            1
Weiro            1
agwa             1
joe              1
Fist             1
sneyldat         1
DreamCrusher     1
AJugOrNot        1
derptank         1
Ether            1
Akawa658         1
Brutallio        1
GodzOnlyFear     1
Mehradba         1
Ryland           1
SupremeCourt     1
Meatbawler       1
ShardAtlas       1
Myrmeleo         1
ThorSmash        1
comeandsee       1
Jason            1
SanT             1
Razzl            1
Name: GameOpponent, dtype: int64