In [2]:
from sqlalchemy import create_engine

engine = create_engine('mysql://9cb054_testdb:paladinlol!@MYSQL5008.Smarterasp.net:3306/db_9cb054_testdb')

# engine = create_engine('mysql://dsi_student:9cb054_testdb@dsi.http://mysql5008.smarterasp.net/:3306/db_9cb054_testdb')

In [3]:
pd.read_sql("SHOW tables", con=engine)

   Tables_in_db_9cb054_testdb
0                        card
1                    carddraw
2                    cardturn
3                        deck
4                        game
5                        hand
6                minionattack
7                mulligancard
8                opponentdeck
9            opponentdeckcard
10                       turn
11                       user
12                   userdeck
13               userdeckcard

In [5]:
sql = """
SELECT * FROM game
ORDER BY GameID DESC
"""

train = pd.read_sql(sql, con=engine)
train.head()

,GameID,GameUserName,GameUserClass,GameOpponent,GameOpponentClass,GameStart,GameEnd,GameType,GameRank,Victory,Coin,ReplayText
0,1435,thall,Thrall,The Innkeeper,Malfurion Stormrage,2016-05-20 15:54:18,2016-05-20 15:54:18,,0, ,,You draw Argent Squire#You draw Sir Finley M...
1,1434,thall,Thrall,The Innkeeper,Garrosh Hellscream,2016-05-20 09:42:59,2016-05-20 09:42:59,Constructed,0, ,,You draw Argent Horserider#You draw Flameton...
2,1433,Jayford,Malfurion Stormrage,The Innkeeper,Jaina Proudmoore,2016-05-19 23:01:56,2016-05-19 23:01:56,,0,, ,You draw Disciple of CThun#You draw Mire Kee...
3,1432,Jayford,Guldan,The Innkeeper,Valeera Sanguinar,2016-05-19 22:48:54,2016-05-19 22:48:54,,0, ,,You draw Sea Giant#You draw Darkshire Counci...
4,1431,Jayford,Guldan,The Innkeeper,Anduin Wrynn,2016-05-19 22:39:56,2016-05-19 22:39:56,,0, ,,You draw Leeroy Jenkins#You draw Darkshire C...